### PR TITLE
WIP: Websockets

### PR DESCRIPTION
**Pull request by davecusatis**

### CODE REVIEW

**Comment by davecusatis** [comment]
I'm a dingle

**Comment by DotStarMoney** [comment]
Whats with the websockets ep? Also, you gotta gitignore the bilge folders my man.

**Comment by davecusatis** [comment]
Work in progress/concept idea for streaming. Which bildge folders are not in gitignore? This and the other pull request remove any bilge folders.

**Comment by davecusatis** [comment]
Don't merge this

**Comment by davecusatis** [comment]
Git is borked on this branch atm. we want to merge the other pull request, and rebase this one.

**Comment by davecusatis** [comment]
should not have merged this one LMAO

**Pull request merged**
